SELECT NFE.NUNOTA,
       NFE.XML
  FROM TGFCAB CAB
 INNER JOIN TGFNFE NFE
    ON NFE.NUNOTA = CAB.NUNOTA
 WHERE CAB.AD_ENVIADOLINCROS IS NULL
   AND CAB.STATUSNFE = 'A'
   AND CAB.DTNEG >= TRUNC(SYSDATE) - 100